spring.application.name=sb.e-com
server.port=8080

spring.h2.console.enabled = true
spring.h2.console.path=/h2-console
spring.datasource.url = jdbc:h2:mem:test

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true

project.image = image/

spring.security.expirationInMs = 3600000
spring.security.secret = ThisIsMyStrongJWTSecretKeyForSpringBoot2026

spring.security.jwtCookieName = ecommJwtCookie